

CREATE SEQUENCE beneficio_seq START WITH 1 INCREMENT BY 1;

-
CREATE TABLE BENEFICIO (
  ID BIGINT PRIMARY KEY DEFAULT nextval('beneficio_seq'),
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO VARCHAR(255),
  VALOR NUMERIC(15,2) NOT NULL,
  ATIVO BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0
);


CREATE SEQUENCE conta_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE CONTA (
  ID BIGINT PRIMARY KEY DEFAULT nextval('conta_seq'),
  TITULAR VARCHAR(100) NOT NULL,
  SALDO NUMERIC(15,2) NOT NULL DEFAULT 0,
  ATIVA BOOLEAN DEFAULT TRUE,
  VERSION BIGINT DEFAULT 0
);

s
CREATE SEQUENCE transferencia_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE TRANSFERENCIA (
  ID BIGINT PRIMARY KEY DEFAULT nextval('transferencia_seq'),
  CONTA_ORIGEM_ID BIGINT NOT NULL,
  CONTA_DESTINO_ID BIGINT NOT NULL,
  VALOR NUMERIC(15,2) NOT NULL,
  DATA_TRANSFERENCIA TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  FOREIGN KEY (CONTA_ORIGEM_ID) REFERENCES CONTA(ID),
  FOREIGN KEY (CONTA_DESTINO_ID) REFERENCES CONTA(ID)
);
